### ISSUE TITLE
关于AppEnvironment的类型

### ISSUE THREAD

**Issue by iwantFB** [Lebron1992/WeChat-SwiftUI#1]
您好，请问一下为什么AppEnvironment要定义成一个枚举类型呢？Struct 不是更好吗？语意更加清晰一点

**Comment by Lebron1992** [comment]
> 

@iwantFB
因为 `AppEnvironment` 不需要创建任何实例对象，相当于命名空间的作用。如果你用 `struct`，那么就可以创建对象 `AppEnvironment()`，但这个对象是无任何意义的，我们并不需要。所以用 `enum` 是最好的。
 
关于 `enum` / `class` / `struct` 如何选择。我写过一个总结，你可以看下：https://juejin.cn/post/6875138387292979213

**Comment by Lebron1992** [comment]
你好。
因为 AppEnvironment 不需要任何创建任何实例对象，相当于命名空间的作用。如果你用 struct，那么就可以创建对象 AppEnvironment()，但这个对象是无任何意义的，我们并不需要。所以用 enum 是最好的。

关于 enum / class / struct 如何选择。我写过一个总结，你可以看下：https://juejin.cn/post/6875138387292979213

From: iwantFB ***@***.***>
Date: Friday, May 6, 2022 at 11:50
To: Lebron1992/WeChat-SwiftUI ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Lebron1992/WeChat-SwiftUI] 关于AppEnvironment的类型 (Issue #1)

您好，请问一下为什么AppEnvironment要定义成一个枚举类型呢？Struct 不是更好吗？语意更加清晰一点

―
